import type { Phase } from "./types";

export const seedPhases: Phase[] = [
  {
    id: "before-departure",
    title: "Before Departure",
    description: "Leave Seoul with the essentials handled and fewer unknowns in your carry-on.",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    tasks: [
      {
        id: "print-documents",
        title: "Print important documents",
        note: "Visa, passport copies, insurance certificate, booking confirmations, and emergency contacts.",
        deadline: "2026-06-07",
        status: "completed",
      },
      {
        id: "prepare-insurance",
        title: "Prepare insurance",
        note: "Confirm coverage starts before the flight and keep the policy PDF offline.",
        deadline: "2026-06-10",
        status: "in_progress",
      },
      {
        id: "buy-adapter",
        title: "Buy adapter",
        note: "Korea to EU plug adapter plus one small power strip.",
        deadline: "2026-06-18",
        status: "available",
      },
      {
        id: "backup-laptop",
        title: "Backup laptop",
        note: "Create one cloud backup and one encrypted external backup before packing.",
        deadline: "2026-06-22",
        status: "available",
      },
    ],
  },
  {
    id: "arrival-survival",
    title: "Arrival Survival",
    description: "Get signal, movement, food, and a first rhythm in Berlin without over-planning.",
    startDate: "2026-07-01",
    endDate: "2026-07-14",
    tasks: [
      {
        id: "prepare-esim",
        title: "Prepare SIM/eSIM",
        note: "Install before departure and test activation instructions while still on Wi-Fi.",
        deadline: "2026-07-01",
        status: "available",
        dependsOn: ["print-documents"],
      },
      {
        id: "public-transport",
        title: "Set up public transport",
        note: "Install BVG/VBB app and decide whether a Deutschlandticket makes sense.",
        deadline: "2026-07-03",
        status: "available",
        dependsOn: ["prepare-esim"],
      },
      {
        id: "grocery-route",
        title: "Find a repeatable grocery route",
        note: "Choose one easy supermarket, one backup, and one nearby late option.",
        deadline: "2026-07-08",
        status: "available",
        dependsOn: ["public-transport"],
      },
    ],
  },
  {
    id: "airbnb-period",
    title: "Airbnb Period",
    description: "Use the temporary stay as a quiet launchpad for housing and registration.",
    startDate: "2026-07-15",
    endDate: "2026-08-31",
    tasks: [
      {
        id: "search-wg",
        title: "Search WG rooms",
        note: "Prepare a short intro message and save a few search filters.",
        deadline: "2026-07-18",
        status: "available",
      },
      {
        id: "anmeldung-docs",
        title: "Prepare Anmeldung documents",
        note: "Passport, form, Wohnungsgeberbestätigung, and appointment confirmation.",
        deadline: "2026-07-25",
        status: "available",
        dependsOn: ["search-wg"],
      },
      {
        id: "open-bank",
        title: "Open bank account",
        note: "Pick a bank that works with your address and identity documents.",
        deadline: "2026-08-05",
        status: "available",
        dependsOn: ["anmeldung-docs"],
      },
    ],
  },
  {
    id: "long-term-settlement",
    title: "Long-Term Settlement",
    description: "Shift from landing mode into a sustainable Berlin routine and career track.",
    startDate: "2026-09-01",
    endDate: "2026-10-31",
    tasks: [
      {
        id: "update-cv",
        title: "Update CV",
        note: "Create a Berlin-ready developer CV and matching LinkedIn summary.",
        deadline: "2026-09-08",
        status: "available",
        dependsOn: ["open-bank"],
      },
      {
        id: "apply-dev-jobs",
        title: "Apply to developer jobs",
        note: "Start with a small batch of focused applications and track responses.",
        deadline: "2026-09-20",
        status: "available",
        dependsOn: ["update-cv"],
      },
      {
        id: "settlement-ritual",
        title: "Choose a weekly settling ritual",
        note: "A walk, market visit, quiet cafe hour, or call home that makes the week feel anchored.",
        deadline: "2026-09-30",
        status: "available",
      },
    ],
  },
];
