import type { InventoryCategory, InventoryItem, PackingContainer, Phase } from "./types";

export const seedPhases: Phase[] = [
  {
    id: "before-departure",
    title: "Before Departure",
    description: "Leave Seoul with the essentials handled and fewer unknowns in your carry-on.",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    tasks: [
      {
        id: "print-documents",
        title: "Print important documents",
        note: "Visa, passport copies, insurance certificate, booking confirmations, and emergency contacts.",
        deadline: "2026-06-07",
        status: "completed",
      },
      {
        id: "prepare-insurance",
        title: "Prepare insurance",
        note: "Confirm coverage starts before the flight and keep the policy PDF offline.",
        deadline: "2026-06-10",
        status: "in_progress",
      },
      {
        id: "buy-adapter",
        title: "Buy adapter",
        note: "Korea to EU plug adapter plus one small power strip.",
        deadline: "2026-06-18",
        status: "available",
      },
      {
        id: "backup-laptop",
        title: "Backup laptop",
        note: "Create one cloud backup and one encrypted external backup before packing.",
        deadline: "2026-06-22",
        status: "available",
      },
    ],
  },
  {
    id: "arrival-survival",
    title: "Arrival Survival",
    description: "Get signal, movement, food, and a first rhythm in Berlin without over-planning.",
    startDate: "2026-07-01",
    endDate: "2026-07-14",
    tasks: [
      {
        id: "prepare-esim",
        title: "Prepare SIM/eSIM",
        note: "Install before departure and test activation instructions while still on Wi-Fi.",
        deadline: "2026-07-01",
        status: "available",
        dependsOn: ["print-documents"],
      },
      {
        id: "public-transport",
        title: "Set up public transport",
        note: "Install BVG/VBB app and decide whether a Deutschlandticket makes sense.",
        deadline: "2026-07-03",
        status: "available",
        dependsOn: ["prepare-esim"],
      },
      {
        id: "grocery-route",
        title: "Find a repeatable grocery route",
        note: "Choose one easy supermarket, one backup, and one nearby late option.",
        deadline: "2026-07-08",
        status: "available",
        dependsOn: ["public-transport"],
      },
    ],
  },
  {
    id: "airbnb-period",
    title: "Airbnb Period",
    description: "Use the temporary stay as a quiet launchpad for housing and registration.",
    startDate: "2026-07-15",
    endDate: "2026-08-31",
    tasks: [
      {
        id: "search-wg",
        title: "Search WG rooms",
        note: "Prepare a short intro message and save a few search filters.",
        deadline: "2026-07-18",
        status: "available",
      },
      {
        id: "anmeldung-docs",
        title: "Prepare Anmeldung documents",
        note: "Passport, form, Wohnungsgeberbestätigung, and appointment confirmation.",
        deadline: "2026-07-25",
        status: "available",
        dependsOn: ["search-wg"],
      },
      {
        id: "open-bank",
        title: "Open bank account",
        note: "Pick a bank that works with your address and identity documents.",
        deadline: "2026-08-05",
        status: "available",
        dependsOn: ["anmeldung-docs"],
      },
    ],
  },
  {
    id: "long-term-settlement",
    title: "Long-Term Settlement",
    description: "Shift from landing mode into a sustainable Berlin routine and career track.",
    startDate: "2026-09-01",
    endDate: "2026-10-31",
    tasks: [
      {
        id: "update-cv",
        title: "Update CV",
        note: "Create a Berlin-ready developer CV and matching LinkedIn summary.",
        deadline: "2026-09-08",
        status: "available",
        dependsOn: ["open-bank"],
      },
      {
        id: "apply-dev-jobs",
        title: "Apply to developer jobs",
        note: "Start with a small batch of focused applications and track responses.",
        deadline: "2026-09-20",
        status: "available",
        dependsOn: ["update-cv"],
      },
      {
        id: "settlement-ritual",
        title: "Choose a weekly settling ritual",
        note: "A walk, market visit, quiet cafe hour, or call home that makes the week feel anchored.",
        deadline: "2026-09-30",
        status: "available",
      },
    ],
  },
];

export const seedInventoryCategories: InventoryCategory[] = [
  { id: "misc", name: "Misc" },
  { id: "kitchen", name: "Kitchen" },
  { id: "clothing", name: "Clothing" },
  { id: "desk", name: "Desk" },
  { id: "cosmetics", name: "Cosmetics" },
  { id: "bathroom", name: "Bathroom" },
  { id: "bedding", name: "Bedding" },
  { id: "important-items", name: "Important Items" },
  { id: "exercise", name: "Exercise" },
];

export const seedPackingContainers: PackingContainer[] = [
  { id: "suitcase-26", name: "26-inch suitcase" },
  { id: "suitcase-20", name: "20-inch suitcase" },
  { id: "backpack", name: "Backpack" },
  { id: "hip-bag", name: "Hip bag" },
  { id: "future-korea-shipment", name: "Future Korea shipment" },
];

const item = (
  id: string,
  name: string,
  categoryId: string,
  options: Partial<Pick<InventoryItem, "topic" | "quantity" | "status" | "buyLocation" | "priority" | "notes" | "containerId" | "packed">> = {},
): InventoryItem => ({
  id,
  name,
  categoryId,
  topic: options.topic,
  quantity: options.quantity ?? "1",
  status: options.status ?? "already_have",
  buyLocation: options.buyLocation ?? "none",
  priority: options.priority ?? "medium",
  notes: options.notes,
  containerId: options.containerId,
  packed: options.packed ?? false,
});

export const seedInventoryItems: InventoryItem[] = [
  item("rice-cooker", "rice cooker", "kitchen", { priority: "high", containerId: "future-korea-shipment" }),
  item("portable-cutlery", "portable cutlery", "kitchen", { containerId: "backpack" }),
  item("extra-chopsticks", "extra chopsticks", "kitchen", { quantity: "2 sets" }),
  item("tumbler", "tumbler", "kitchen", { containerId: "backpack" }),
  item("salt", "salt", "kitchen"),
  item("kitchen-scissors", "scissors", "kitchen"),
  item("microwave-rice-container", "microwave rice container", "kitchen", { status: "need_to_buy", buyLocation: "germany" }),
  item("brita-water-filter", "Brita water filter", "kitchen", { status: "need_to_buy", buyLocation: "germany" }),
  item("rubber-gloves", "rubber gloves", "kitchen", { status: "need_to_buy", buyLocation: "germany" }),
  item("towels", "towels", "clothing", { quantity: "2-3" }),
  item("underwear", "underwear", "clothing", { quantity: "7 sets" }),
  item("socks", "socks", "clothing", { quantity: "10" }),
  item("t-shirts", "t-shirts", "clothing", { quantity: "7" }),
  item("pants", "pants", "clothing", { quantity: "3" }),
  item("shorts", "shorts", "clothing", { quantity: "2" }),
  item("cardigan", "cardigan", "clothing"),
  item("hoodie", "hoodie", "clothing"),
  item("windbreakers", "windbreakers", "clothing", { quantity: "2" }),
  item("crossbody-bags", "crossbody bags", "clothing", { quantity: "2-3" }),
  item("shoes", "shoes", "clothing", { quantity: "3" }),
  item("hangers", "hangers", "clothing"),
  item("laundry-detergent", "laundry detergent", "clothing", { status: "need_to_buy", buyLocation: "germany" }),
  item("swimsuit", "swimsuit", "clothing", { status: "optional" }),
  item("beach-towel", "beach towel", "clothing", { status: "optional" }),
  item("german-book", "German book", "desk", { containerId: "backpack" }),
  item("pencil-case", "pencil case", "desk"),
  item("stationery", "stationery", "desk"),
  item("desk-scissors", "scissors", "desk"),
  item("measuring-tape", "measuring tape", "desk"),
  item("tape", "tape", "desk"),
  item("alcohol-wipes", "alcohol wipes", "desk"),
  item("toner-pads", "toner pads", "cosmetics"),
  item("fixer", "fixer", "cosmetics"),
  item("cushion-foundation", "cushion foundation", "cosmetics"),
  item("sunscreen", "sunscreen", "cosmetics", { priority: "high" }),
  item("physiogel", "physiogel", "cosmetics"),
  item("cleansing-water", "cleansing water", "cosmetics"),
  item("cotton-pads", "cotton pads", "cosmetics"),
  item("eyebrow-razor", "eyebrow razor", "cosmetics"),
  item("eyeliner", "eyeliner", "cosmetics"),
  item("soap", "soap", "bathroom"),
  item("toothpaste-toothbrush", "toothpaste/toothbrush", "bathroom", { priority: "high" }),
  item("toothbrush-holder", "toothbrush holder", "bathroom"),
  item("pads", "one month of pads", "bathroom", { priority: "high" }),
  item("hair-dryer", "hair dryer", "bathroom"),
  item("mini-hair-straightener", "mini hair straightener", "bathroom"),
  item("bathroom-slippers", "bathroom slippers", "bathroom", { status: "need_to_buy", buyLocation: "germany" }),
  item("pillow", "pillow if possible", "bedding", { status: "optional" }),
  item("electric-blanket", "electric blanket", "bedding"),
  item("documents", "documents", "important-items", { status: "important", priority: "high", containerId: "backpack" }),
  item("laptop", "laptop", "important-items", { status: "important", priority: "high", containerId: "backpack" }),
  item("laptop-stand", "laptop stand", "important-items"),
  item("chargers", "chargers", "important-items", { status: "important", priority: "high", containerId: "backpack" }),
  item("airpods", "AirPods", "important-items", { containerId: "hip-bag" }),
  item("keyboard", "keyboard", "important-items"),
  item("power-strip", "power strip", "important-items"),
  item("mouse", "mouse", "important-items"),
  item("mouse-pad", "mouse pad", "important-items"),
  item("ipad", "iPad", "important-items", { containerId: "backpack" }),
  item("spare-phone-case", "spare phone case", "important-items"),
  item("spare-screen-protector", "spare screen protector", "important-items"),
  item("medicine", "medicine", "important-items", { status: "important", priority: "high", containerId: "hip-bag" }),
  item("sunglasses", "sunglasses", "important-items"),
  item("keyring", "keyring", "important-items"),
  item("massager", "massager", "exercise"),
  item("gua-sha", "gua sha", "exercise"),
  item("peanut-ball", "peanut ball", "exercise"),
  item("dumbbells", "dumbbells", "exercise", { status: "need_to_buy", buyLocation: "germany" }),
  item("helmet", "helmet", "misc"),
  item("folding-umbrella", "folding umbrella", "misc"),
  item("slippers", "slippers", "misc"),
  item("cleaning-supplies", "cleaning supplies", "misc", { status: "need_to_buy", buyLocation: "germany" }),
];
